"""Multi-layer context compression.

Claude Code uses a 4-layer strategy:
  1. HISTORY_SNIP   - trim old tool outputs to a one-line summary
  2. Microcompact   - LLM-powered summary of old turns (cached)
  3. CONTEXT_COLLAPSE - aggressive compression when nearing hard limit
  4. Autocompact    - periodic background compaction

Folium implements a 3-layer progressive strategy:
  Layer 1 (snip)      - 60%: trim long tool outputs, keep head/tail chars
  Layer 2 (prune)     - 80%: replace trimmed tool outputs with placeholders
  Layer 3 (summarize) - 90%: incremental LLM summary + protected user messages
"""

from __future__ import annotations
from typing import TYPE_CHECKING

from .config import DEFAULT_MAX_CONTEXT_TOKENS
from .token_estimator import estimate_message_tokens, estimate_text_tokens

if TYPE_CHECKING:
    from .llm import LLM

DEFAULT_RESERVED_OUTPUT_TOKENS = 20_000
DEFAULT_PROTECTED_USER_TOKENS = 20_000
TOOL_OUTPUT_TRIM_THRESHOLD_CHARS = 4096
TOOL_OUTPUT_TRIM_KEEP_CHARS = 1536
TOOL_OUTPUT_TRIM_MARKER = "trimmed to save context"
SUMMARY_PREFIX = (
    "Another language model has started working on this problem and generated a summary of its reasoning. "
    "You also have access to the tool states that were used. "
    "Please continue based on the work already completed and avoid duplicating effort. "
    "Below is the summary generated by that model, use this information to assist your own analysis:"
)


def _approx_tokens(text: str) -> int:
    """Estimate token count for content not covered by API usage."""
    return estimate_text_tokens(text)


def estimate_tokens(messages: list[dict]) -> int:
    return estimate_message_tokens(messages)


class LayerReport(dict):
    def __bool__(self) -> bool:
        return bool(self.get("changed"))


def _tool_report_item(message: dict) -> dict:
    return {
        "tool_call_id": message.get("tool_call_id"),
        "name": message.get("name"),
    }


def _layer_report(name: str, tools: list[dict]) -> LayerReport:
    return LayerReport({
        "name": name,
        "changed": bool(tools),
        "tools": tools,
    })


def _summarize_report(changed: bool, delta_message_count: int,
                      protected_user_count: int, used_llm: bool,
                      fallback_used: bool, before_message_count: int,
                      after_message_count: int) -> LayerReport:
    return LayerReport({
        "name": "summarize",
        "changed": changed,
        "delta_message_count": delta_message_count,
        "protected_user_count": protected_user_count,
        "before_message_count": before_message_count,
        "after_message_count": after_message_count,
        "used_llm": used_llm,
        "fallback_used": fallback_used,
    })


class ContextManager:
    def __init__(self, max_tokens: int = DEFAULT_MAX_CONTEXT_TOKENS,
                 reserved_output_tokens: int = DEFAULT_RESERVED_OUTPUT_TOKENS,
                 protected_user_tokens: int = DEFAULT_PROTECTED_USER_TOKENS):
        self.max_tokens = max_tokens
        self.reserved_output_tokens = max(0, reserved_output_tokens)
        self.protected_user_tokens = max(1, protected_user_tokens)
        self.input_budget_tokens = max(1, max_tokens - self.reserved_output_tokens)
        # layer thresholds (fraction of input budget after reserving output tokens)
        self._snip_at = int(self.input_budget_tokens * 0.60)    # 60% -> snip tool outputs
        self._prune_at = int(self.input_budget_tokens * 0.80)    # 80% -> prune to placeholders
        self._summarize_at = int(self.input_budget_tokens * 0.90)  # 90% -> LLM summarize

    def maybe_compress(self, messages: list[dict], llm: LLM | None = None,
                       real_tokens: int | None = None) -> dict:
        """Apply compression layers as needed and return an observability report.

        Args:
            real_tokens: Actual token count from LLM API (prompt_tokens + completion_tokens).
                         Falls back to estimate_tokens() if not provided.
        """
        current = real_tokens if real_tokens is not None else estimate_tokens(messages)
        report = {"compressed": False, "layers": []}

        # Layer 1: trim verbose tool outputs
        if current > self._snip_at:
            layer = self._snip_tool_outputs(messages)
            if layer["changed"]:
                report["compressed"] = True
                report["layers"].append(layer)
                current = estimate_tokens(messages)

        # Layer 2: prune trimmed tool outputs to placeholders
        if current > self._prune_at:
            layer = self._prune_tool_outputs(messages)
            if layer["changed"]:
                report["compressed"] = True
                report["layers"].append(layer)
                current = estimate_tokens(messages)

        # Layer 3: LLM-powered summarization of old turns
        if current > self._summarize_at:
            layer = self._summarize_old(messages, llm)
            if layer["changed"]:
                report["compressed"] = True
                report["layers"].append(layer)
                current = estimate_tokens(messages)

        return report

    @staticmethod
    def _snip_tool_outputs(messages: list[dict]) -> dict:
        """Layer 1: Trim very long tool results while preserving head and tail.

        This mirrors Claude Code's HISTORY_SNIP which replaces old tool outputs
        with a one-line summary to reclaim context space.
        """
        tools = []
        for m in messages:
            if m.get("role") != "tool":
                continue
            content = m.get("content", "")
            if len(content) <= TOOL_OUTPUT_TRIM_THRESHOLD_CHARS:
                continue
            trimmed = (
                content[:TOOL_OUTPUT_TRIM_KEEP_CHARS]
                + f"\n... ({len(content)} chars total, {TOOL_OUTPUT_TRIM_MARKER}) ...\n"
                + content[-TOOL_OUTPUT_TRIM_KEEP_CHARS:]
            )
            m["content"] = trimmed
            tools.append(_tool_report_item(m))
        return _layer_report("trim", tools)

    @staticmethod
    def _prune_tool_outputs(messages: list[dict]) -> dict:
        """Layer 2: Replace already-trimmed tool outputs with compact placeholders.

        Tool outputs that were truncated by Layer 1 still carry several lines of
        content. This layer replaces them with a single-line placeholder to
        release more space at zero LLM cost.
        """
        PRUNED = "[Content compacted to save context]"
        tools = []
        for m in messages:
            if m.get("role") != "tool":
                continue
            content = m.get("content", "")
            if not content:
                continue
            # only prune outputs that were already trimmed by Layer 1
            if TOOL_OUTPUT_TRIM_MARKER not in content:
                continue
            m["content"] = PRUNED
            tools.append(_tool_report_item(m))
        return _layer_report("prune", tools)

    def _summarize_old(self, messages: list[dict], llm: LLM | None) -> dict:
        """Layer 3: Incrementally summarize history and protect user messages."""
        before_message_count = len(messages)
        if not messages:
            return _summarize_report(False, 0, 0, False, False, 0, 0)

        existing_summary = self._extract_existing_summary(messages)
        delta = self._delta_messages(messages)
        if not delta and existing_summary:
            return _summarize_report(False, 0, 0, False, False, before_message_count, before_message_count)

        summary, used_llm, fallback_used = self._get_incremental_summary(existing_summary, delta, llm)
        protected_users = self._collect_protected_user_messages(messages)
        messages.clear()
        messages.extend(protected_users)
        messages.append(self._summary_message(summary))
        return _summarize_report(
            True,
            len(delta),
            len(protected_users),
            used_llm,
            fallback_used,
            before_message_count,
            len(messages),
        )

    def _summary_message(self, summary: str) -> dict:
        return {
            "role": "user",
            "content": f"{SUMMARY_PREFIX}\n{summary}",
        }

    @staticmethod
    def _is_summary_message(message: dict) -> bool:
        if message.get("role") != "user":
            return False
        content = message.get("content") or ""
        return f"{SUMMARY_PREFIX}\n" in content

    @staticmethod
    def _summary_text(message: dict) -> str:
        content = message.get("content") or ""
        marker = f"{SUMMARY_PREFIX}\n"
        idx = content.find(marker)
        if idx >= 0:
            return content[idx + len(marker):]
        return ""

    def _extract_existing_summary(self, messages: list[dict]) -> str:
        summaries = [
            self._summary_text(message)
            for message in messages
            if self._is_summary_message(message)
        ]
        return "\n\n".join(summary for summary in summaries if summary)

    def _delta_messages(self, messages: list[dict]) -> list[dict]:
        return [
            message
            for message in messages
            if not self._is_summary_message(message) and not message.get("_protected")
        ]

    def _collect_protected_user_messages(self, messages: list[dict]) -> list[dict]:
        selected: list[dict] = []
        used = 0

        for message in reversed(messages):
            if message.get("role") != "user" or self._is_summary_message(message):
                continue
            content = message.get("content") or ""
            tokens = estimate_text_tokens(str(content))
            if used + tokens <= self.protected_user_tokens:
                selected.append({"role": "user", "content": content, "_protected": True})
                used += tokens
                continue
            if not selected:
                selected.append({"role": "user", "content": content, "_protected": True})
            break

        selected.reverse()
        return selected

    def _get_incremental_summary(self, existing_summary: str, delta_messages: list[dict],
                                 llm: LLM | None) -> tuple[str, bool, bool]:
        if not existing_summary:
            return self._get_summary(delta_messages, llm)

        delta = self._flatten(delta_messages)
        if not delta:
            return existing_summary, False, False

        if llm:
            try:
                resp = llm.chat(
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "You are performing context checkpoint compression. "
                                "Create a handoff summary for the next LLM that will continue this task. "
                                "Include:\n"
                                "- Current progress and key decisions made\n"
                                "- Important context, constraints, or user preferences\n"
                                "- Remaining work (clear next steps)\n"
                                "- Any critical data, examples, or references needed to continue\n"
                                "Be concise and structured. Focus on helping the next LLM seamlessly continue the work."
                            ),
                        },
                        {
                            "role": "user",
                            "content": (
                                f"Existing summary:\n{existing_summary}\n\n"
                                f"New messages to incorporate:\n{delta[:15000]}"
                            ),
                        },
                    ],
                )
                return resp.content, True, False
            except Exception:
                pass

        extracted = self._extract_key_info(delta_messages)
        if extracted and extracted != "(no extractable context)":
            return f"{existing_summary}\n\nRecent update: {extracted}", False, True
        return existing_summary, False, True

    def _get_summary(self, messages: list[dict], llm: LLM | None) -> tuple[str, bool, bool]:
        """Generate summary via LLM or fallback to extraction."""
        flat = self._flatten(messages)

        if llm:
            try:
                resp = llm.chat(
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "You are performing context checkpoint compression. "
                                "Create a handoff summary for the next LLM that will continue this task. "
                                "Include:\n"
                                "- Current progress and key decisions made\n"
                                "- Important context, constraints, or user preferences\n"
                                "- Remaining work (clear next steps)\n"
                                "- Any critical data, examples, or references needed to continue\n"
                                "Be concise and structured. Focus on helping the next LLM seamlessly continue the work."
                            ),
                        },
                        {"role": "user", "content": flat[:15000]},
                    ],
                )
                return resp.content, True, False
            except Exception:
                pass

        # fallback: extract key lines
        return self._extract_key_info(messages), False, True

    @staticmethod
    def _flatten(messages: list[dict]) -> str:
        parts = []
        for m in messages:
            role = m.get("role", "?")
            text = m.get("content", "") or ""
            if text:
                parts.append(f"[{role}] {text[:400]}")
        return "\n".join(parts)

    @staticmethod
    def _extract_key_info(messages: list[dict]) -> str:
        """Fallback: extract file paths, errors, and decisions without LLM."""
        import re
        files_seen = set()
        errors = []
        decisions = []

        for m in messages:
            text = m.get("content", "") or ""
            # extract file paths
            for match in re.finditer(r'[\w./\-]+\.\w{1,5}', text):
                files_seen.add(match.group())
            # extract error lines
            for line in text.splitlines():
                if 'error' in line.lower() or 'Error' in line:
                    errors.append(line.strip()[:150])

        parts = []
        if files_seen:
            parts.append(f"Files touched: {', '.join(sorted(files_seen)[:20])}")
        if errors:
            parts.append(f"Errors seen: {'; '.join(errors[:5])}")
        return "\n".join(parts) or "(no extractable context)"
