"""Multi-layer context compression.

Claude Code uses a 4-layer strategy:
  1. HISTORY_SNIP   - trim old tool outputs to a one-line summary
  2. Microcompact   - LLM-powered summary of old turns (cached)
  3. CONTEXT_COLLAPSE - aggressive compression when nearing hard limit
  4. Autocompact    - periodic background compaction

Folium implements a 3-layer progressive strategy:
  Pre-layer            - 50%: fold exact duplicate tool outputs
  Layer 1 (snip)      - 60%/70%: trim primary/secondary tool outputs, keep head/tail chars
  Layer 2 (prune)     - 80%: replace trimmed primary/default tool outputs with placeholders
  Layer 3 (summarize) - 90%: incremental LLM summary + protected user messages
"""

from __future__ import annotations

import hashlib
from typing import TYPE_CHECKING

from .config import DEFAULT_MAX_CONTEXT_TOKENS
from .token_estimator import estimate_message_tokens, estimate_text_tokens

if TYPE_CHECKING:
    from .llm import LLM

DEFAULT_RESERVED_OUTPUT_TOKENS = 20_000
DEFAULT_PROTECTED_USER_TOKENS = 20_000
DEFAULT_PROTECTED_INITIAL_USER_MESSAGES = 2
TOOL_OUTPUT_TRIM_THRESHOLD_CHARS = 4096
TOOL_OUTPUT_TRIM_KEEP_CHARS = 1536
TOOL_OUTPUT_TRIM_MARKER = "trimmed to save context"
TOOL_OUTPUT_DEDUPE_THRESHOLD_CHARS = 200
TOOL_OUTPUT_DEDUPE_PLACEHOLDER = (
    "[Duplicate tool output folded: same content as later tool result]"
)
RECENT_TOOL_ROUNDS_TO_KEEP = 2

# Exempt tools: never compress these outputs
TOOL_COMPRESS_EXEMPT: set[str] = set()

# Tool compression tiers:
#   primary   - trim at 60% threshold (default)
#   secondary - trim when context usage reaches 70%
TOOL_COMPRESSION_TIER: dict[str, str] = {
    "bash": "primary",
    "grep": "primary",
    "glob": "primary",
    "read_file": "secondary",
    "agent": "secondary",
    "_default": "primary",
}

SUMMARY_PREFIX = (
    "Another language model has started working on this problem and generated a summary of its reasoning. "
    "You also have access to the tool states that were used. "
    "Please continue based on the work already completed and avoid duplicating effort. "
    "Below is the summary generated by that model, use this information to assist your own analysis:"
)


def _approx_tokens(text: str) -> int:
    """Estimate token count for content not covered by API usage."""
    return estimate_text_tokens(text)


def estimate_tokens(messages: list[dict]) -> int:
    return estimate_message_tokens(messages)


class LayerReport(dict):
    def __bool__(self) -> bool:
        return bool(self.get("changed"))


def _tool_report_item(message: dict) -> dict:
    return {
        "tool_call_id": message.get("tool_call_id"),
        "name": message.get("name"),
    }


def _layer_report(name: str, tools: list[dict]) -> LayerReport:
    return LayerReport({
        "name": name,
        "changed": bool(tools),
        "tools": tools,
    })


def _summarize_report(changed: bool, delta_message_count: int,
                      protected_user_count: int, used_llm: bool,
                      fallback_used: bool, before_message_count: int,
                      after_message_count: int) -> LayerReport:
    return LayerReport({
        "name": "summarize",
        "changed": changed,
        "delta_message_count": delta_message_count,
        "protected_user_count": protected_user_count,
        "before_message_count": before_message_count,
        "after_message_count": after_message_count,
        "used_llm": used_llm,
        "fallback_used": fallback_used,
    })


class ContextManager:
    def __init__(self, max_tokens: int = DEFAULT_MAX_CONTEXT_TOKENS,
                 reserved_output_tokens: int = DEFAULT_RESERVED_OUTPUT_TOKENS,
                 protected_user_tokens: int = DEFAULT_PROTECTED_USER_TOKENS,
                 protected_initial_user_messages: int = DEFAULT_PROTECTED_INITIAL_USER_MESSAGES):
        self.max_tokens = max_tokens
        self.reserved_output_tokens = max(0, reserved_output_tokens)
        self.protected_user_tokens = max(1, protected_user_tokens)
        self.protected_initial_user_messages = max(0, protected_initial_user_messages)
        self.input_budget_tokens = max(1, max_tokens - self.reserved_output_tokens)
        # layer thresholds (fraction of input budget after reserving output tokens)
        self._dedupe_at = int(self.input_budget_tokens * 0.50)  # 50% -> fold duplicate tool outputs
        self._snip_at = int(self.input_budget_tokens * 0.60)    # 60% -> snip tool outputs
        self._secondary_snip_at = int(self.input_budget_tokens * 0.70)  # 70% -> snip secondary tools
        self._prune_at = int(self.input_budget_tokens * 0.80)    # 80% -> prune to placeholders
        self._summarize_at = int(self.input_budget_tokens * 0.90)  # 90% -> LLM summarize

    def maybe_compress(self, messages: list[dict], llm: LLM | None = None,
                       real_tokens: int | None = None) -> dict:
        """Apply compression layers as needed and return an observability report.

        Args:
            real_tokens: Actual token count from LLM API (prompt_tokens + completion_tokens).
                         Falls back to estimate_tokens() if not provided.
        """
        current = real_tokens if real_tokens is not None else estimate_tokens(messages)
        context_usage_ratio = current / self.input_budget_tokens if self.input_budget_tokens > 0 else 0.0
        report = {"compressed": False, "layers": []}

        # Pre-layer: fold exact duplicate tool outputs before lossy trimming.
        if current > self._dedupe_at:
            layer = self._dedupe_tool_outputs(messages)
            if layer["changed"]:
                report["compressed"] = True
                report["layers"].append(layer)
                current = estimate_tokens(messages)
                context_usage_ratio = current / self.input_budget_tokens if self.input_budget_tokens > 0 else 0.0

        # Layer 1: trim verbose tool outputs
        if current > self._snip_at:
            secondary_usage_ratio = self._secondary_snip_at / self.input_budget_tokens
            layer = self._snip_tool_outputs(
                messages,
                context_usage_ratio,
                secondary_usage_ratio,
                RECENT_TOOL_ROUNDS_TO_KEEP,
            )
            if layer["changed"]:
                report["compressed"] = True
                report["layers"].append(layer)
                current = estimate_tokens(messages)

        # Layer 2: prune trimmed primary/default tool outputs to placeholders
        if current > self._prune_at:
            layer = self._prune_tool_outputs(messages)
            if layer["changed"]:
                report["compressed"] = True
                report["layers"].append(layer)
                current = estimate_tokens(messages)

        # Layer 3: LLM-powered summarization of old turns
        if current > self._summarize_at:
            layer = self._summarize_old(messages, llm)
            if layer["changed"]:
                report["compressed"] = True
                report["layers"].append(layer)
                current = estimate_tokens(messages)

        return report

    @staticmethod
    def _dedupe_tool_outputs(messages: list[dict]) -> dict:
        """Fold exact duplicate tool outputs, preserving the latest full result."""
        tools = []
        content_hashes: set[str] = set()

        for m in reversed(messages):
            if m.get("role") != "tool":
                continue

            tool_name = m.get("name", "_default")
            if tool_name in TOOL_COMPRESS_EXEMPT:
                continue

            content = m.get("content", "")
            if not isinstance(content, str):
                continue
            if len(content) < TOOL_OUTPUT_DEDUPE_THRESHOLD_CHARS:
                continue

            content_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
            if content_hash in content_hashes:
                m["content"] = TOOL_OUTPUT_DEDUPE_PLACEHOLDER
                tools.append(_tool_report_item(m))
                continue

            content_hashes.add(content_hash)

        tools.reverse()
        return _layer_report("dedupe", tools)

    @staticmethod
    def _snip_tool_outputs(messages: list[dict], context_usage_ratio: float = 0.0,
                           secondary_usage_ratio: float = 0.7,
                           recent_tool_rounds_to_keep: int = RECENT_TOOL_ROUNDS_TO_KEEP) -> dict:
        """Layer 1: Trim very long tool results while preserving head and tail.

        This mirrors Claude Code's HISTORY_SNIP which replaces old tool outputs
        with a one-line summary to reclaim context space.

        Args:
            context_usage_ratio: Current context usage as fraction of input budget.
                                 Secondary tools only trim when this reaches secondary_usage_ratio.
        """
        tools = []
        protected_tool_call_ids = _recent_tool_call_ids(messages, recent_tool_rounds_to_keep)
        for m in messages:
            if m.get("role") != "tool":
                continue
            if m.get("tool_call_id") in protected_tool_call_ids:
                continue

            tool_name = m.get("name", "_default")

            # exempt tools are never compressed
            if tool_name in TOOL_COMPRESS_EXEMPT:
                continue

            # secondary tools only trim when context is tight
            tier = TOOL_COMPRESSION_TIER.get(tool_name, "primary")
            if tier == "secondary" and context_usage_ratio < secondary_usage_ratio:
                continue

            content = m.get("content", "")
            if len(content) <= TOOL_OUTPUT_TRIM_THRESHOLD_CHARS:
                continue
            trimmed = (
                content[:TOOL_OUTPUT_TRIM_KEEP_CHARS]
                + f"\n... ({len(content)} chars total, {TOOL_OUTPUT_TRIM_MARKER}) ...\n"
                + content[-TOOL_OUTPUT_TRIM_KEEP_CHARS:]
            )
            m["content"] = trimmed
            tools.append(_tool_report_item(m))
        return _layer_report("trim", tools)

    @staticmethod
    def _prune_tool_outputs(messages: list[dict]) -> dict:
        """Layer 2: Replace already-trimmed primary/default tool outputs with compact placeholders.

        Tool outputs that were truncated by Layer 1 still carry several lines of
        content. This layer replaces lower-priority tool outputs with a
        single-line placeholder to release more space at zero LLM cost.
        """
        PRUNED = "[Content compacted to save context]"
        tools = []
        for m in messages:
            if m.get("role") != "tool":
                continue
            tool_name = m.get("name", "_default")
            tier = TOOL_COMPRESSION_TIER.get(tool_name, "primary")
            if tier == "secondary":
                continue
            content = m.get("content", "")
            if not content:
                continue
            # only prune outputs that were already trimmed by Layer 1
            if TOOL_OUTPUT_TRIM_MARKER not in content:
                continue
            m["content"] = PRUNED
            tools.append(_tool_report_item(m))
        return _layer_report("prune", tools)

    def _summarize_old(self, messages: list[dict], llm: LLM | None) -> dict:
        """Layer 3: Incrementally summarize history and protect user messages."""
        before_message_count = len(messages)
        if not messages:
            return _summarize_report(False, 0, 0, False, False, 0, 0)

        existing_summary = self._extract_existing_summary(messages)
        delta = self._delta_messages(messages)
        if not delta and existing_summary:
            return _summarize_report(False, 0, 0, False, False, before_message_count, before_message_count)

        summary, used_llm, fallback_used = self._get_incremental_summary(existing_summary, delta, llm)
        protected_users = self._collect_protected_user_messages(messages)
        messages.clear()
        messages.extend(protected_users)
        messages.append(self._summary_message(summary))
        return _summarize_report(
            True,
            len(delta),
            len(protected_users),
            used_llm,
            fallback_used,
            before_message_count,
            len(messages),
        )

    def _summary_message(self, summary: str) -> dict:
        return {
            "role": "user",
            "content": f"{SUMMARY_PREFIX}\n{summary}",
        }

    @staticmethod
    def _is_summary_message(message: dict) -> bool:
        if message.get("role") != "user":
            return False
        content = message.get("content") or ""
        return f"{SUMMARY_PREFIX}\n" in content

    @staticmethod
    def _summary_text(message: dict) -> str:
        content = message.get("content") or ""
        marker = f"{SUMMARY_PREFIX}\n"
        idx = content.find(marker)
        if idx >= 0:
            return content[idx + len(marker):]
        return ""

    def _extract_existing_summary(self, messages: list[dict]) -> str:
        summaries = [
            self._summary_text(message)
            for message in messages
            if self._is_summary_message(message)
        ]
        return "\n\n".join(summary for summary in summaries if summary)

    def _delta_messages(self, messages: list[dict]) -> list[dict]:
        return [
            message
            for message in messages
            if not self._is_summary_message(message) and not message.get("_protected")
        ]

    def _collect_protected_user_messages(self, messages: list[dict]) -> list[dict]:
        user_messages = [
            (index, message)
            for index, message in enumerate(messages)
            if message.get("role") == "user" and not self._is_summary_message(message)
        ]
        selected_indexes: set[int] = set()

        for index, _ in user_messages[:self.protected_initial_user_messages]:
            selected_indexes.add(index)

        recent_used = 0
        recent_indexes: set[int] = set()
        for index, message in reversed(user_messages):
            content = message.get("content") or ""
            tokens = estimate_text_tokens(str(content))
            if recent_used + tokens <= self.protected_user_tokens:
                recent_indexes.add(index)
                recent_used += tokens
                continue
            if not recent_indexes:
                recent_indexes.add(index)
            break

        selected_indexes.update(recent_indexes)
        return [
            {"role": "user", "content": message.get("content") or "", "_protected": True}
            for index, message in user_messages
            if index in selected_indexes
        ]

    def _get_incremental_summary(self, existing_summary: str, delta_messages: list[dict],
                                 llm: LLM | None) -> tuple[str, bool, bool]:
        if not existing_summary:
            return self._get_summary(delta_messages, llm)

        delta = self._flatten(delta_messages)
        if not delta:
            return existing_summary, False, False

        if llm:
            try:
                resp = llm.chat(
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "You are performing context checkpoint compression. "
                                "Create a handoff summary for the next LLM that will continue this task. "
                                "Include:\n"
                                "- Current progress and key decisions made\n"
                                "- Important context, constraints, or user preferences\n"
                                "- Remaining work (clear next steps)\n"
                                "- Any critical data, examples, or references needed to continue\n"
                                "Be concise and structured. Focus on helping the next LLM seamlessly continue the work."
                            ),
                        },
                        {
                            "role": "user",
                            "content": (
                                f"Existing summary:\n{existing_summary}\n\n"
                                f"New messages to incorporate:\n{delta[:15000]}"
                            ),
                        },
                    ],
                )
                return resp.content, True, False
            except Exception:
                pass

        extracted = self._extract_key_info(delta_messages)
        if extracted and extracted != "(no extractable context)":
            return f"{existing_summary}\n\nRecent update: {extracted}", False, True
        return existing_summary, False, True

    def _get_summary(self, messages: list[dict], llm: LLM | None) -> tuple[str, bool, bool]:
        """Generate summary via LLM or fallback to extraction."""
        flat = self._flatten(messages)

        if llm:
            try:
                resp = llm.chat(
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "You are performing context checkpoint compression. "
                                "Create a handoff summary for the next LLM that will continue this task. "
                                "Include:\n"
                                "- Current progress and key decisions made\n"
                                "- Important context, constraints, or user preferences\n"
                                "- Remaining work (clear next steps)\n"
                                "- Any critical data, examples, or references needed to continue\n"
                                "Be concise and structured. Focus on helping the next LLM seamlessly continue the work."
                            ),
                        },
                        {"role": "user", "content": flat[:15000]},
                    ],
                )
                return resp.content, True, False
            except Exception:
                pass

        # fallback: extract key lines
        return self._extract_key_info(messages), False, True

    @staticmethod
    def _flatten(messages: list[dict]) -> str:
        parts = []
        for m in messages:
            role = m.get("role", "?")
            text = m.get("content", "") or ""
            if text:
                parts.append(f"[{role}] {text[:400]}")
        return "\n".join(parts)

    @staticmethod
    def _extract_key_info(messages: list[dict]) -> str:
        """Fallback: extract file paths, errors, and decisions without LLM."""
        import re
        files_seen = set()
        errors = []
        decisions = []

        for m in messages:
            text = m.get("content", "") or ""
            # extract file paths
            for match in re.finditer(r'[\w./\-]+\.\w{1,5}', text):
                files_seen.add(match.group())
            # extract error lines
            for line in text.splitlines():
                if 'error' in line.lower() or 'Error' in line:
                    errors.append(line.strip()[:150])

        parts = []
        if files_seen:
            parts.append(f"Files touched: {', '.join(sorted(files_seen)[:20])}")
        if errors:
            parts.append(f"Errors seen: {'; '.join(errors[:5])}")
        return "\n".join(parts) or "(no extractable context)"


def _recent_tool_call_ids(messages: list[dict], rounds_to_keep: int) -> set[str]:
    if rounds_to_keep <= 0:
        return set()

    protected: set[str] = set()
    rounds_seen = 0
    in_tool_block = False

    for message in reversed(messages):
        if message.get("role") == "tool":
            tool_call_id = message.get("tool_call_id")
            if tool_call_id:
                protected.add(tool_call_id)
            in_tool_block = True
            continue

        if in_tool_block:
            rounds_seen += 1
            if rounds_seen >= rounds_to_keep:
                break
            in_tool_block = False

    return protected
